"""Deterministic local LLM provider — no network calls, no API keys.

This is what makes the entire platform runnable offline: `docker compose up`
with zero secrets still produces a fully populated dashboard, because every
trace can be generated by this provider instead of a real one. Determinism
(same prompt + model -> same output) also makes it usable inside pytest for
routing/evaluation/regression tests without flaky network mocks.

Behavior is driven by each model's `ModelProfile` (quality tier, latency
prior, hallucination tendency) so weaker/cheaper models plausibly produce
lower-faithfulness answers and stronger/pricier ones produce better answers —
giving the evaluation and routing subsystems something real to differentiate.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import random
import re
import time

from sentinellm.llm.base import (
    LLMErrorKind,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    ProviderError,
)
from sentinellm.pricing.catalog import get_profile

_FABRICATIONS = [
    "This was independently confirmed by a 2021 audit.",
    "According to internal benchmarks, this holds in 99.8% of cases.",
    "This feature has been available since the product's initial launch.",
    "The vendor's engineering team verified this personally.",
    "This is guaranteed under the standard service agreement.",
]

_UNSTABLE_MARKERS = ("unstable", "flaky", "down")


def _seeded_rng(*parts: str) -> random.Random:
    digest = hashlib.sha256("|".join(parts).encode()).hexdigest()
    return random.Random(int(digest[:16], 16))


def _estimate_tokens(text: str) -> int:
    return max(1, round(len(text.split()) * 1.35))


def _extract_question_and_context(request: LLMRequest) -> tuple[str, str]:
    user_msgs = [m.content for m in request.messages if m.role == "user"]
    question = user_msgs[-1] if user_msgs else ""
    context = "\n".join(m.content for m in request.messages if m.role == "system")
    return question, context


_JUDGE_SECTION_RE = re.compile(
    r"QUESTION:\n(?P<question>.*?)\n\nCONTEXT:\n(?P<context>.*?)\n\nANSWER:\n(?P<answer>.*)",
    re.DOTALL,
)


def _word_overlap(a: str, b: str) -> float:
    words_a = set(re.findall(r"[a-z0-9]+", a.lower()))
    words_b = set(re.findall(r"[a-z0-9]+", b.lower()))
    if not words_a or not words_b:
        return 0.0
    return len(words_a & words_b) / len(words_a | words_b)


def _build_judge_payload(request: LLMRequest, rng: random.Random) -> tuple[str, int]:
    """Simulates an LLM judge's structured JSON response. Returns (content, attempt).

    A small deterministic fraction of first attempts return malformed JSON so
    JudgeEvaluator's retry path is genuinely exercised end to end, not just
    unit-tested against a hand-built malformed string.
    """
    attempt = int(request.metadata.get("judge_attempt", 1))
    user_content = "\n".join(m.content for m in request.messages if m.role == "user")
    match = _JUDGE_SECTION_RE.search(user_content)
    context_text = match.group("context") if match else ""
    answer_text = match.group("answer") if match else user_content

    overlap = _word_overlap(context_text, answer_text)
    # Blend overlap with a little deterministic noise so the judge isn't a pure
    # restatement of the deterministic evaluators.
    score = max(0.0, min(1.0, overlap * 0.8 + rng.uniform(0.0, 0.25)))
    confidence = round(rng.uniform(0.55, 0.97), 2)

    evidence: list[str] = []
    if context_text.strip():
        for sentence in context_text.split(". ")[:3]:
            sentence = sentence.strip()
            if sentence and _word_overlap(sentence, answer_text) > 0:
                evidence.append(sentence.rstrip(".") + ".")
            if len(evidence) >= 2:
                break

    reasoning = (
        f"answer overlaps {overlap:.0%} of context vocabulary; "
        f"{'well grounded' if score >= 0.6 else 'weakly grounded' if score >= 0.3 else 'largely unsupported'}"
    )
    payload = {
        "score": round(score, 3),
        "reasoning": reasoning,
        "evidence": evidence,
        "confidence": confidence,
    }
    content = json.dumps(payload)

    malform_roll = _seeded_rng(user_content, "judge-malform").random()
    if attempt == 1 and malform_roll < 0.2:
        content = content[: max(10, len(content) // 2)]  # truncated -> invalid JSON
    return content, attempt


class MockProvider(LLMProvider):
    name = "mock"
    _skip_sleep = False  # overridden by TimingMockProvider

    def supports_model(self, model: str) -> bool:
        return model.startswith("mock:") or ":" not in model

    async def complete(self, request: LLMRequest) -> LLMResponse:
        model_id = request.model if request.model.startswith("mock:") else f"mock:{request.model}"
        profile = get_profile(model_id)
        rng = _seeded_rng(model_id, request.messages[-1].content if request.messages else "")

        if any(marker in model_id for marker in _UNSTABLE_MARKERS) and rng.random() < 0.6:
            raise ProviderError(
                LLMErrorKind.PROVIDER_ERROR, f"{model_id} simulated outage", retryable=True
            )

        latency_ms = max(
            40.0, rng.gauss(profile.avg_latency_ms_prior, profile.avg_latency_ms_prior * 0.2)
        )
        if not self._skip_sleep:
            await asyncio.sleep(min(latency_ms, 60) / 1000)

        if request.metadata.get("response_schema") == "judge":
            content, _attempt = _build_judge_payload(request, rng)
            input_tokens = _estimate_tokens("\n".join(m.content for m in request.messages))
            output_tokens = _estimate_tokens(content)
            return LLMResponse(
                content=content,
                model=model_id,
                provider=self.name,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                latency_ms=round(latency_ms, 2),
                finish_reason="stop",
            )

        question, context = _extract_question_and_context(request)
        sentences: list[str] = []
        if context.strip():
            grounded = context.strip().split(". ")[:2]
            for s in grounded:
                s = s.strip().rstrip(".")
                if s:
                    sentences.append(f"{s}.")
        if not sentences:
            sentences.append(
                f"Regarding '{question.strip().rstrip('?')}', here is a concise answer."
            )
        else:
            sentences.insert(
                0, f"In response to your question about {question.strip().rstrip('?').lower()}:"
            )

        if rng.random() < profile.hallucination_tendency:
            # Replace (not merely append to) a grounded sentence: a real
            # hallucination typically displaces what should have been the
            # correct detail rather than politely tacking on an extra one, and
            # this keeps the fabrication a large-enough share of a short
            # answer for the faithfulness/hallucination evaluators to notice.
            fabrication = rng.choice(_FABRICATIONS)
            if len(sentences) > 1:
                sentences[-1] = fabrication
            else:
                sentences.append(fabrication)

        content = " ".join(sentences)
        input_tokens = _estimate_tokens(
            (request.messages and "\n".join(m.content for m in request.messages)) or ""
        )
        output_tokens = _estimate_tokens(content)

        return LLMResponse(
            content=content,
            model=model_id,
            provider=self.name,
            input_tokens=input_tokens,
            output_tokens=min(output_tokens, request.max_tokens),
            latency_ms=round(latency_ms, 2),
            finish_reason="stop",
        )


class TimingMockProvider(MockProvider):
    """Variant used by perf benchmarks: skips the simulated network sleep
    entirely (rather than merely re-measuring around it), so benchmark
    numbers reflect the pipeline's own overhead."""

    _skip_sleep = True

    async def complete(self, request: LLMRequest) -> LLMResponse:
        start = time.perf_counter()
        response = await super().complete(request)
        elapsed_ms = (time.perf_counter() - start) * 1000
        return LLMResponse(
            content=response.content,
            model=response.model,
            provider=response.provider,
            input_tokens=response.input_tokens,
            output_tokens=response.output_tokens,
            latency_ms=round(elapsed_ms, 3),
            finish_reason=response.finish_reason,
        )
