"""add trace_feedback table

Revision ID: 549e23060b48
Revises: 5c4cbe0eb71e
Create Date: 2026-09-03 07:13:11.533004

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '549e23060b48'
down_revision: Union[str, None] = '5c4cbe0eb71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id', name='uq_trace_feedback_trace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_feedback')
    # ### end Alembic commands ###
