"""rollout quality regression guard and one active rollout per app

Revision ID: 5f0188256a91
Revises: 941bb75681a6
Create Date: 2026-09-20 22:43:12.681714

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f0188256a91'
down_revision: Union[str, None] = '941bb75681a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'model_rollouts',
        sa.Column('max_quality_regression', sa.Float(), nullable=False, server_default='0.1'),
    )
    op.alter_column('model_rollouts', 'max_quality_regression', server_default=None)

    # The unique index below can't be built if an application already has
    # more than one active rollout — possible before this migration, since
    # "one active rollout per app" was only checked in the service (racy
    # under concurrent creates). Keep the newest active one (the one
    # `get_active_rollout` already treats as authoritative) and close the
    # older ones out.
    op.execute(
        """
        UPDATE model_rollouts
        SET stage = 'rolled_back',
            traffic_pct = 0,
            outcome_reason = 'superseded by a newer active rollout (migration)'
        WHERE stage IN ('running', 'paused')
          AND created_at < (
              SELECT MAX(newer.created_at) FROM model_rollouts AS newer
              WHERE newer.application_id = model_rollouts.application_id
                AND newer.stage IN ('running', 'paused')
          )
        """
    )
    op.create_index('uq_model_rollouts_one_active_per_app', 'model_rollouts', ['application_id'], unique=True, postgresql_where=sa.text("stage IN ('running', 'paused')"), sqlite_where=sa.text("stage IN ('running', 'paused')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_model_rollouts_one_active_per_app', table_name='model_rollouts', postgresql_where=sa.text("stage IN ('running', 'paused')"), sqlite_where=sa.text("stage IN ('running', 'paused')"))
    op.drop_column('model_rollouts', 'max_quality_regression')
    # ### end Alembic commands ###
