"""add model rollouts table

Revision ID: 941bb75681a6
Revises: adf92132b98c
Create Date: 2026-09-07 20:38:52.469480

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '941bb75681a6'
down_revision: Union[str, None] = 'adf92132b98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_rollouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=200), nullable=False),
    sa.Column('incumbent_model', sa.String(length=100), nullable=False),
    sa.Column('challenger_model', sa.String(length=100), nullable=False),
    sa.Column('traffic_pct', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('quality_floor', sa.Float(), nullable=False),
    sa.Column('max_error_rate', sa.Float(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('step_pct', sa.Float(), nullable=False),
    sa.Column('max_pct', sa.Float(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_rollouts_application_created', 'model_rollouts', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_rollouts_application_created', table_name='model_rollouts')
    op.drop_table('model_rollouts')
    # ### end Alembic commands ###
