"""add model health tracking and api key application scoping

Revision ID: adf92132b98c
Revises: ea737d6d62ee
Create Date: 2026-09-07 06:45:55.772206

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adf92132b98c'
down_revision: Union[str, None] = 'ea737d6d62ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'api_keys',
        sa.Column('scoped_to_application', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('api_keys', 'scoped_to_application', server_default=None)
    op.add_column(
        'models',
        sa.Column('status_auto', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('models', 'status_auto', server_default=None)
    op.add_column('models', sa.Column('status_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'status_reason')
    op.drop_column('models', 'status_auto')
    op.drop_column('api_keys', 'scoped_to_application')
    # ### end Alembic commands ###
