"""add application cost budget and trace tags

Revision ID: ea737d6d62ee
Revises: 549e23060b48
Create Date: 2026-09-03 08:05:41.502368

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea737d6d62ee'
down_revision: Union[str, None] = '549e23060b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('daily_cost_budget', sa.Float(), nullable=True))
    op.add_column(
        'traces',
        sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.alter_column('traces', 'tags', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'tags')
    op.drop_column('applications', 'daily_cost_budget')
    # ### end Alembic commands ###
